<?php
	define('HTTP', 'http://');
	//define('HTTP', 'https://');
	define('TIT', ' | Metedología VAC con PHP');
	define('DIRMOR', 'MORENOCL/');
	define('DIRACT', 'ACTIONJF/');
	define('__DIRIMG__', $_SERVER['DOCUMENT_ROOT']."/vac/img/");
	define('URL', HTTP.'localhost:81/vac/');
	//define('URL', HTTP.'localhost/vac/');
	define('IMG', URL.'img/');
	define('SIST', URL.'sistem/');
	define('XCEL', URL.'excel/');
	define('PDFS', URL.'pdf/');
	define('ACTI', URL.DIRACT);
	define('PLUG', URL.'plugins/');
	define('FMMA', 'https://frankmorenoalburqueque.com/');
	define('LOGOF', FMMA.'images/logo.png');
	define('FACE', 'https://www.facebook.com/FrankMartinMA/');
	define('TWIT', 'https://www.facebook.com/FrankMartinMA/');
	define('INST', 'https://www.facebook.com/frankmartinmoreno/');